### ISSUE TITLE
Standings update before player information 

### ISSUE THREAD

**Issue by malikh22** [bellosil21/pokerTexasHoldEm#12]
1: Waited for my turn
2: pressed check
3: Waited
4: Standings showed that I had $0, but the info in the lower right still showed $22

This is not good because conflicting information can confuse the player.

**Comment by marcial21** [comment]
we will review this

**Comment by hoser21** [comment]
After review, we have not gotten this state to reoccur. Please let us know if you come across this issue again.

**Comment by malikh22** [comment]
I did not see this issue again. It could have been a problem with the network in general.
