### ISSUE TITLE
dummy showing cards issue

### ISSUE THREAD

**Issue by dendinge21** [bellosil21/pokerTexasHoldEm#3]
Steps to recreate
1. Run game
2. pressed call 
3. One dumb AI showed their cards, the other did not.
4. After pressing call and raise bet a few times, the other dumb AI showed their cards. The way you said you implemented your dumb AI is that they are supposed to their cards right away

**Comment by marcial21** [comment]
We have recreated this scenario and it seemed to work fine. Let us know if you run into this issue again.

**Comment by dendinge21** [comment]
They fixed the issue!!!
