### ISSUE TITLE
SeekBar and Text View issue 

### ISSUE THREAD

**Issue by pascuad21** [bellosil21/pokerTexasHoldEm#5]
1.Run Game 
2.Finish a round of playing
2. Set SeekBar to zero
--------------------------------
The text view that displays the number of chips should be 0 but says 100 during the beginning of a new round.

**Comment by marcial21** [comment]
This displays the number of chips you are raising. We have it set to default as 100. If it were 0, than it would mean you are raising 0 chips which wouldn't make sense. That would just be a call action.

**Comment by pascuad21** [comment]
Alright my bad.
