### ISSUE TITLE
Toast message in spanish when should be english

### ISSUE THREAD

**Issue by torkelso19** [bellosil21/pokerTexasHoldEm#6]
Step 1: Begin Game
Step 2: Try to check.
Step 3: Toast message is in spanish

If you choose english in the settings and then try to make a move that isn't valid the toast is in spanish.

**Comment by marcial21** [comment]
yeah i got it

**Comment by hoser21** [comment]
This has been fixed in the next release. See #10.

**Comment by torkelso19** [comment]
Yes this has been fixed!
