### ISSUE TITLE
Toast messages non-descriptive

### ISSUE THREAD

**Issue by robinsph21** [bellosil21/pokerTexasHoldEm#9]
Each toast message just talks about a player's turn, sometimes which isn't actually what the problem is most times, especially when it involves betting/checking/calling. Maybe it was just a buffer of toasts, but I think they could be improved.

**Comment by hoser21** [comment]
Please add clarification on your issue. I do not understand if you are claiming our toasts are displaying improperly. Our toast messages are meant to be simple (notify the player it is their turn or submitted an illegal move), so it does not clutter the screen with text. I will close this issue for the meantime.
